// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../desktop/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Invoke(action: $models.Action): Promise<$models.InvokeResult> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2371333820, action) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Refresh(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4023310423) as any;
    return $resultPromise;
}

export function RefreshPlugins(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1097962029) as any;
    return $resultPromise;
}

export function Search(query: string): Promise<$models.Result[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(611293392, query) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SetDesktopEntries(entries: desktop$0.Entry[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1609435692, entries) as any;
    return $resultPromise;
}

export function Status(): Promise<$models.Status> & { cancel(): void } {
    let $resultPromise = $Call.ByID(520844438) as any;
    let $typingPromise = $resultPromise.then(($result) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.InvokeResult.createFrom;
const $$createType1 = $models.Result.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Status.createFrom;
