// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function InstallPlugin(sourcePath: string): $CancellablePromise<$models.InstallPluginResult> {
    return $Call.ByID(3785730508, sourcePath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Invoke(action: $models.Action): $CancellablePromise<$models.InvokeResult> {
    return $Call.ByID(2371333820, action).then(($result: any) => {
        return $$createType1($result);
    });
}

export function InvokePluginAction(request: $models.PluginActionRequest): $CancellablePromise<$models.InvokeResult> {
    return $Call.ByID(270666357, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PluginManagerState(): $CancellablePromise<$models.PluginManagerState> {
    return $Call.ByID(1001963371).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(4023310423);
}

export function RefreshPlugins(): $CancellablePromise<void> {
    return $Call.ByID(1097962029);
}

export function Search(query: string): $CancellablePromise<$models.Result[]> {
    return $Call.ByID(611293392, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SearchWithContext(query: string): $CancellablePromise<$models.Result[]> {
    return $Call.ByID(545013851, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetCapabilityEnabled(pluginID: string, capabilityID: string, enabled: boolean): $CancellablePromise<$models.PluginManagerState> {
    return $Call.ByID(1132286559, pluginID, capabilityID, enabled).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPluginEnabled(id: string, enabled: boolean): $CancellablePromise<$models.PluginManagerState> {
    return $Call.ByID(282791324, id, enabled).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(520844438).then(($result: any) => {
        return $$createType5($result);
    });
}

export function UninstallPlugin(id: string): $CancellablePromise<$models.PluginManagerState> {
    return $Call.ByID(1897719121, id).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.InstallPluginResult.createFrom;
const $$createType1 = $models.InvokeResult.createFrom;
const $$createType2 = $models.PluginManagerState.createFrom;
const $$createType3 = $models.Result.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Status.createFrom;
