// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "../desktop/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Invoke(action: $models.Action): $CancellablePromise<$models.InvokeResult> {
    return $Call.ByID(2371333820, action).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(4023310423);
}

export function RefreshPlugins(): $CancellablePromise<void> {
    return $Call.ByID(1097962029);
}

export function Search(query: string): $CancellablePromise<$models.Result[]> {
    return $Call.ByID(611293392, query).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetDesktopEntries(entries: desktop$0.Entry[]): $CancellablePromise<void> {
    return $Call.ByID(1609435692, entries);
}

export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(520844438).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.InvokeResult.createFrom;
const $$createType1 = $models.Result.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Status.createFrom;
