// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Action {
    "type": string;
    "appId"?: string;
    "command"?: string;
    "text"?: string;
    "pluginId"?: string;
    "commandId"?: string;
    "entryPath"?: string;
    "export"?: string;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export class InvokeResult {
    "type": string;
    "message": string;
    "entryPath"?: string;
    "url"?: string;

    /** Creates a new InvokeResult instance. */
    constructor($$source: Partial<InvokeResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvokeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InvokeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InvokeResult($$parsedSource as Partial<InvokeResult>);
    }
}

export class Result {
    "id": string;
    "title": string;
    "subtitle": string;
    "kind": string;
    "action": Action;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField4_0($$parsedSource["action"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class Status {
    "appCount": number;
    "pluginCount": number;
    "pluginErrorCount": number;
    "pluginRoots": string[];

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("appCount" in $$source)) {
            this["appCount"] = 0;
        }
        if (!("pluginCount" in $$source)) {
            this["pluginCount"] = 0;
        }
        if (!("pluginErrorCount" in $$source)) {
            this["pluginErrorCount"] = 0;
        }
        if (!("pluginRoots" in $$source)) {
            this["pluginRoots"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pluginRoots" in $$parsedSource) {
            $$parsedSource["pluginRoots"] = $$createField3_0($$parsedSource["pluginRoots"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = Action.createFrom;
const $$createType1 = $Create.Array($Create.Any);
