// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "type": string;
    "appId"?: string;
    "command"?: string;
    "text"?: string;
    "pluginId"?: string;
    "capabilityId"?: string;
    "ui"?: string;
    "query"?: string;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export class InstallPluginResult {
    "pluginId": string;
    "installedPath": string;
    "state": PluginManagerState;

    /** Creates a new InstallPluginResult instance. */
    constructor($$source: Partial<InstallPluginResult> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("installedPath" in $$source)) {
            this["installedPath"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = (new PluginManagerState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallPluginResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallPluginResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        return new InstallPluginResult($$parsedSource as Partial<InstallPluginResult>);
    }
}

export class InvokeResult {
    "type": string;
    "message": string;
    "data"?: any;

    /** Creates a new InvokeResult instance. */
    constructor($$source: Partial<InvokeResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvokeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InvokeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InvokeResult($$parsedSource as Partial<InvokeResult>);
    }
}

export class ManagedCapability {
    "id": string;
    "title": string;
    "icon": string;
    "ui": string;
    "keywords": string[];
    "enabled": boolean;

    /** Creates a new ManagedCapability instance. */
    constructor($$source: Partial<ManagedCapability> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("ui" in $$source)) {
            this["ui"] = "";
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = [];
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedCapability {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField4_0($$parsedSource["keywords"]);
        }
        return new ManagedCapability($$parsedSource as Partial<ManagedCapability>);
    }
}

export class ManagedLoadError {
    "path": string;
    "error": string;

    /** Creates a new ManagedLoadError instance. */
    constructor($$source: Partial<ManagedLoadError> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedLoadError instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedLoadError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManagedLoadError($$parsedSource as Partial<ManagedLoadError>);
    }
}

export class ManagedPlugin {
    "id": string;
    "name": string;
    "type": string;
    "version": string;
    "source": string;
    "path": string;
    "permissions": string[];
    "capabilities": ManagedCapability[];
    "enabled": boolean;
    "protected": boolean;
    "uninstallable": boolean;

    /** Creates a new ManagedPlugin instance. */
    constructor($$source: Partial<ManagedPlugin> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = [];
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = [];
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("protected" in $$source)) {
            this["protected"] = false;
        }
        if (!("uninstallable" in $$source)) {
            this["uninstallable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedPlugin instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedPlugin {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField6_0($$parsedSource["permissions"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField7_0($$parsedSource["capabilities"]);
        }
        return new ManagedPlugin($$parsedSource as Partial<ManagedPlugin>);
    }
}

export class PluginActionRequest {
    "pluginId": string;
    "capabilityId": string;
    "action": Action;

    /** Creates a new PluginActionRequest instance. */
    constructor($$source: Partial<PluginActionRequest> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("capabilityId" in $$source)) {
            this["capabilityId"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginActionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginActionRequest {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField2_0($$parsedSource["action"]);
        }
        return new PluginActionRequest($$parsedSource as Partial<PluginActionRequest>);
    }
}

export class PluginManagerState {
    "plugins": ManagedPlugin[];
    "loadErrors": ManagedLoadError[];
    "pluginRoots": string[];
    "userPluginRoot": string;
    "pluginConfigPath": string;

    /** Creates a new PluginManagerState instance. */
    constructor($$source: Partial<PluginManagerState> = {}) {
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }
        if (!("loadErrors" in $$source)) {
            this["loadErrors"] = [];
        }
        if (!("pluginRoots" in $$source)) {
            this["pluginRoots"] = [];
        }
        if (!("userPluginRoot" in $$source)) {
            this["userPluginRoot"] = "";
        }
        if (!("pluginConfigPath" in $$source)) {
            this["pluginConfigPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginManagerState instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginManagerState {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField0_0($$parsedSource["plugins"]);
        }
        if ("loadErrors" in $$parsedSource) {
            $$parsedSource["loadErrors"] = $$createField1_0($$parsedSource["loadErrors"]);
        }
        if ("pluginRoots" in $$parsedSource) {
            $$parsedSource["pluginRoots"] = $$createField2_0($$parsedSource["pluginRoots"]);
        }
        return new PluginManagerState($$parsedSource as Partial<PluginManagerState>);
    }
}

export class Result {
    "id": string;
    "title": string;
    "subtitle": string;
    "kind": string;
    "action": Action;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField4_0($$parsedSource["action"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class Status {
    "appCount": number;
    "pluginCount": number;
    "pluginErrorCount": number;
    "pluginRoots": string[];

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("appCount" in $$source)) {
            this["appCount"] = 0;
        }
        if (!("pluginCount" in $$source)) {
            this["pluginCount"] = 0;
        }
        if (!("pluginErrorCount" in $$source)) {
            this["pluginErrorCount"] = 0;
        }
        if (!("pluginRoots" in $$source)) {
            this["pluginRoots"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pluginRoots" in $$parsedSource) {
            $$parsedSource["pluginRoots"] = $$createField3_0($$parsedSource["pluginRoots"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = PluginManagerState.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ManagedCapability.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Action.createFrom;
const $$createType5 = ManagedPlugin.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ManagedLoadError.createFrom;
const $$createType8 = $Create.Array($$createType7);
