// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "ID": string;
    "Name": string;
    "Comment": string;
    "Exec": string;
    "Icon": string;
    "Categories": string[];
    "Path": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Comment" in $$source)) {
            this["Comment"] = "";
        }
        if (!("Exec" in $$source)) {
            this["Exec"] = "";
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("Categories" in $$source)) {
            this["Categories"] = [];
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Categories" in $$parsedSource) {
            $$parsedSource["Categories"] = $$createField5_0($$parsedSource["Categories"]);
        }
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
